# Generated by Django 4.1.3 on 2022-11-15 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anser',
            new_name='Answer',
        ),
    ]
